server:
  port: 18080
spring:
  application:
    name: back-front
  profiles:
    active: '@environment@'
mybatis:
  type-aliases-package: cn.gorillahug.base.data.model
  mapper-locations: classpath:mapper/*.xml


