spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/back_front?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: root